spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.245.129:3306/user?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 88888888
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.user.entity

logging:
  level:
    root: debug
